# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
#      args:
#        ARG: <ARG>
    image: ift6758/serving
    ports:
     - "0.0.0.0:80:80"
    environment:
      DOCKER_ENV_VAR: COMET_API_KEY
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
      #args:
      #  ARG: <ARG>
    image: ift6758/streamlit
    ports:
      - "127.0.0.1:8080:8080"
    #environment:
    #  OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}
